# tasks file
---
- name: configure | create (local facts) directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d/
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - ufw-configure-facts

- name: configure | update configuration file(s)
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: etc/default/ufw.j2
      dest: /etc/default/ufw
    - src: etc/ansible/facts.d/ufw.fact.j2
      dest: /etc/ansible/facts.d/ufw.fact
  register: configuration
  tags:
    - ufw-configure-facts

- name: configure | reset
  community.general.ufw:
    state: reset
  when:
    - configuration is changed
    - ufw_reset_before_apply
  tags:
    - ufw-configure-reset

- name: configure | default (incoming) policy
  community.general.ufw:
    policy: "{{ ufw_default_incoming_policy }}"
    direction: incoming
  notify: reload ufw
  tags:
    - ufw-configure-default-policy
    - ufw-configure-default-policy-incoming

- name: configure | default (outgoing) policy
  community.general.ufw:
    policy: "{{ ufw_default_outgoing_policy }}"
    direction: outgoing
  notify: reload ufw
  tags:
    - ufw-configure-default-policy
    - ufw-configure-default-policy-outgoing

- name: configure | rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    delete: "{{ item.delete | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    insert_relative_to: "{{ item.insert_relative_to | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    app: "{{ item.app | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    if: "{{ item.if | default(omit) }}"
    interface_in: "{{ item.interface_in | default(omit) }}"
    interface_out: "{{ item.interface_out | default(omit) }}"
    if_in: "{{ if_in | default(omit) }}"
    if_out: "{{ if_out | default(omit) }}"
    direction: "{{ item.direction | default(omit if item.route | default(false) else 'in') }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from: "{{ item.from | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    to: "{{ item.to | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    protocol: "{{ item.protocol | default(omit) }}"
    route: "{{ item.route | default(omit) }}"
    log: "{{ item.log | default(false) }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ ufw_rules }}"
  notify: reload ufw
  tags:
    - ufw-configure-rules

- name: configure | logging
  community.general.ufw:
    logging: "{{ ufw_logging }}"
  notify: reload ufw
  tags:
    - ufw-configure-logging
